// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZJSSAvkNLqMRa7y7V_QJtewqOH9S6Jpk',
    appId: '1:631363015120:web:9e1ac2c9b6b147d78ce9d5',
    messagingSenderId: '631363015120',
    projectId: 'fir-flutter-b1f4d',
    authDomain: 'fir-flutter-b1f4d.firebaseapp.com',
    storageBucket: 'fir-flutter-b1f4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfuz2lPUNaoPnShayLnGHcVoax9wlWR0M',
    appId: '1:631363015120:android:206c371d474f544e8ce9d5',
    messagingSenderId: '631363015120',
    projectId: 'fir-flutter-b1f4d',
    storageBucket: 'fir-flutter-b1f4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdgyhIRhc8jqZhrCfCdGrPTE7j5iQnIwY',
    appId: '1:631363015120:ios:d401554a91d9227f8ce9d5',
    messagingSenderId: '631363015120',
    projectId: 'fir-flutter-b1f4d',
    storageBucket: 'fir-flutter-b1f4d.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdgyhIRhc8jqZhrCfCdGrPTE7j5iQnIwY',
    appId: '1:631363015120:ios:d401554a91d9227f8ce9d5',
    messagingSenderId: '631363015120',
    projectId: 'fir-flutter-b1f4d',
    storageBucket: 'fir-flutter-b1f4d.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZJSSAvkNLqMRa7y7V_QJtewqOH9S6Jpk',
    appId: '1:631363015120:web:72f0ec0dc2e4dc988ce9d5',
    messagingSenderId: '631363015120',
    projectId: 'fir-flutter-b1f4d',
    authDomain: 'fir-flutter-b1f4d.firebaseapp.com',
    storageBucket: 'fir-flutter-b1f4d.appspot.com',
  );
}
